on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  check:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        python-version: 3.9
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install -U flake8
    - name: Lint with flake8
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=255 --statistics
